"use strict";

// Datos de ejemplo. Los primeros diez registros reproducen la imagen.
// Para agregar un empleado: [nombre, cargo, oficina, salario numérico].
const employees = [
  ["Airi Satou", "Accountant", "Tokyo", 162700],
  ["Angelica Ramos", "Chief Executive Officer (CEO)", "London", 1200000],
  ["Ashton Cox", "Junior Technical Author", "San Francisco", 86000],
  ["Bradley Greer", "Software Engineer", "London", 132000],
  ["Brenden Wagner", "Software Engineer", "San Francisco", 206850],
  ["Brielle Williamson", "Integration Specialist", "New York", 372000],
  ["Bruno Nash", "Software Engineer", "London", 163500],
  ["Caesar Vance", "Pre-Sales Support", "New York", 106450],
  ["Cara Stevens", "Sales Assistant", "New York", 145600],
  ["Cedric Kelly", "Senior Javascript Developer", "Edinburgh", 433060],
  ["Charde Marshall", "Regional Director", "San Francisco", 470600],
  ["Colleen Hurst", "Javascript Developer", "San Francisco", 205500],
  ["Dai Rios", "Personnel Lead", "Edinburgh", 217500],
  ["Donna Snider", "Customer Support", "New York", 112000],
  ["Doris Wilder", "Sales Assistant", "Sydney", 85600],
  ["Finn Camacho", "Support Engineer", "San Francisco", 87500],
  ["Fiona Green", "Chief Operating Officer (COO)", "San Francisco", 850000],
  ["Garrett Winters", "Accountant", "Tokyo", 170750],
  ["Gavin Cortez", "Team Leader", "San Francisco", 235500],
  ["Gavin Joyce", "Developer", "Edinburgh", 92575],
  ["Gloria Little", "Systems Administrator", "New York", 237500],
  ["Haley Kennedy", "Senior Marketing Designer", "London", 313500],
  ["Hermione Butler", "Regional Director", "London", 356250],
  ["Herrod Chandler", "Sales Assistant", "San Francisco", 137500],
  ["Hope Fuentes", "Secretary", "San Francisco", 109850],
  ["Howard Hatfield", "Office Manager", "San Francisco", 164500],
  ["Jackson Bradshaw", "Director", "New York", 645750],
  ["Jena Gaines", "Office Manager", "London", 90560],
  ["Jenette Caldwell", "Development Lead", "New York", 345000],
  ["Jennifer Acosta", "Junior Javascript Developer", "Edinburgh", 75650],
  ["Jennifer Chang", "Regional Director", "Singapore", 357650],
  ["Jonas Alexander", "Developer", "San Francisco", 86500],
  ["Lael Greer", "Systems Administrator", "London", 103500],
  ["Martena Mccray", "Post-Sales Support", "Edinburgh", 324050],
  ["Michael Bruce", "Javascript Developer", "Singapore", 183000],
  ["Michael Silva", "Marketing Designer", "London", 198500],
  ["Michelle House", "Integration Specialist", "Sydney", 95400],
  ["Olivia Liang", "Support Engineer", "Singapore", 234500],
  ["Paul Byrd", "Chief Financial Officer (CFO)", "New York", 725000],
  ["Prescott Bartlett", "Technical Author", "London", 145000],
  ["Quinn Flynn", "Support Lead", "Edinburgh", 342000],
  ["Rhona Davidson", "Integration Specialist", "Tokyo", 327900],
  ["Sakura Yamamoto", "Support Engineer", "Tokyo", 139575],
  ["Serge Baldwin", "Data Coordinator", "Singapore", 138575],
  ["Shad Decker", "Regional Director", "Edinburgh", 183000],
  ["Shou Itou", "Regional Marketing", "Tokyo", 163000],
  ["Sonya Frost", "Software Engineer", "Edinburgh", 103600],
  ["Suki Burks", "Developer", "London", 114500],
  ["Tatyana Fitzpatrick", "Regional Director", "London", 385750],
  ["Thor Walton", "Developer", "New York", 98540],
  ["Tiger Nixon", "System Architect", "Edinburgh", 320800],
  ["Timothy Mooney", "Office Manager", "London", 136200],
  ["Unity Butler", "Marketing Designer", "San Francisco", 85675],
  ["Vivian Harrell", "Financial Controller", "San Francisco", 452500],
  ["Yuri Berry", "Chief Marketing Officer (CMO)", "New York", 675000],
  ["Zenaida Frank", "Software Engineer", "New York", 125250],
  ["Zorita Serrano", "Software Engineer", "San Francisco", 115000]
].map(([name, position, office, salary]) => ({ name, position, office, salary }));
